version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
      # If you have a dev key for encryption, set it here if needed.
      # RAILS_MASTER_KEY: some_key
    # command: ["bin/rails", "server", "-b", "0.0.0.0"]
    # The command can also be set in the Dockerfile, or here.

# Since we're using SQLite, no separate database service is necessary. The database file will be stored in your project.
