#docker-compose.yml
version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    environment:
      RAILS_ENV: development
    stdin_open: true
    tty: true
#    command: ["bin/rails", "server", "-b", "0.0.0.0"]
#    command: ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
    command: sh -c "bundle exec rails db:create db:migrate db:seed && bundle exec rails server -b '0.0.0.0'"

volumes:
  bundle:
