version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    environment:
      RAILS_ENV: development
#    command: ["bin/rails", "server", "-b", "0.0.0.0"]

volumes:
  bundle:
